/ambotw1_ns:
        joyremap_node:
                ros__parameters:
                                axes: ["axes[1]", "axes[0]", "axes[2]","axes[3]","axes[4]"]
                                buttons: ["buttons[0]","buttons[1]","buttons[2]","buttons[3]","buttons[4]","buttons[5]"]
